# Use the official nginx image
FROM nginx:latest

# Copy the front-end files into Nginx HTML directory
COPY ./softy-pinko-front-end /var/www/html/softy-pinko-front-end

# Copy our Nginx config
COPY ./softy-pinko-front-end.conf /etc/nginx/conf.d/default.conf
