# Use latest Ubuntu
FROM ubuntu:latest

# Update and upgrade
RUN apt-get update && apt-get upgrade -y

# Install Python3 and pip3
RUN apt-get install -y python3 python3-pip

# Remove externally managed warning
RUN rm /usr/lib/python*/EXTERNALLY-MANAGED

# Install Flask using pip3
RUN pip3 install flask

# Set working directory
WORKDIR /app

# Copy API file
COPY ./api.py /app/api.py

# Expose Flask port
EXPOSE 5252

# Run the Flask server
CMD ["python3", "api.py"]
