# Use the latest Ubuntu image
FROM ubuntu:latest

# Update APT and upgrade installed packages
RUN apt-get update && apt-get upgrade -y

# Run a command that echoes "Hello, World!" when the container starts
CMD ["echo", "Hello, World!"]
