# softy-pinko-front-end.conf

server {
    # Port 9000-də dinləyin
    listen 9000;
    server_name softy_pinko_front_end;

    # Bütün sorğular üçün root-u təyin edin
    location / {
        # Front-end fayllarının Docker image-dəki yolu
        root   /var/www/html/softy-pinko-front-end;
        # Əsas indeks faylını təyin edin
        index  index.html;
        # Hər hansı bir fayl tapılmazsa, indeksə qayıt (SPA üçün tipik)
        try_files $uri $uri/ =404;
    }
}
