FROM ubuntu:latest

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y python3 python3-pip

RUN pip3 install flask
RUN pip3 install flask-cors # 🟢 flask-cors quraşdırılması

WORKDIR /app
COPY ./api.py /app/api.py

EXPOSE 5252 # Port 5252-ni ifşa edin

CMD ["python3", "api.py"]
